# GuitarTrainer Logging Configuration
# Separate logging configuration as requested

logging:
  version: 1
  disable_existing_loggers: false
  
  formatters:
    standard:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
    detailed:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - Line:%(lineno)d - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"

  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: standard
      stream: ext://sys.stdout
      
    main_file:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: standard
      filename: logs/main.log
      maxBytes: 10485760  # 10MB
      backupCount: 5
      
    video_input_file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: logs/video_input.log
      maxBytes: 10485760  # 10MB
      backupCount: 5
      
    pose_detection_file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: logs/pose_detection.log
      maxBytes: 10485760  # 10MB
      backupCount: 5
      
    gui_file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: logs/gui.log
      maxBytes: 10485760  # 10MB
      backupCount: 5

  loggers:
    video_input:
      level: DEBUG
      handlers: [console, video_input_file]
      propagate: false
      
    pose_detection:
      level: DEBUG
      handlers: [console, pose_detection_file]
      propagate: false
      
    gui:
      level: DEBUG
      handlers: [console, gui_file]
      propagate: false

  root:
    level: INFO
    handlers: [console, main_file]
